zephyrtargetcontrol: fix missing native_sysroot
fix
Exception: TypeError: QemuTargetZephyr.__init__() got an unexpected
keyword argument 'native_sysroot'

Signed-off-by: Lee Chee Yang <chee.yang.lee@intel.com>